name: Generate gRPC code
on:
  push:
    branches: main
    paths:
      - 'rpc/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate Go Code By Buf
        run: |
          go install github.com/bufbuild/buf/cmd/buf@latest
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install connectrpc.com/connect/cmd/protoc-gen-connect-go@latest
          export PATH="$PATH:$(go env GOPATH)/bin"
          buf generate

      - name: Commit and Push Generated Code
        run: |
          git config user.name "gRPC Bot"
          git config user.email "grpc@example.com"
          git pull
          git add -A
          git commit -m "chore: regenerate grpc code"
          git push