name: Generate gRPC code
on:
  push:
    branches: main
    # paths:
    #   - 'rpc/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Buf
        run: |
          npm install @bufbuild/buf
          go install github.com/fullstorydev/grpcurl/cmd/grpcurl@latest
          go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
          go install connectrpc.com/connect/cmd/protoc-gen-connect-go@latest
          export PATH="$PATH:$(go env GOPATH)/bin"

      - name: Generate Go Code
        run: |
          npx buf generate

      - name: Commit and Push Generated Code
        run: |
          git config user.name "gRPC Bot"
          git config user.email "grpc@example.com"
          git pull
          git add -A
          git commit -m "chore: regenerate grpc code"
          git push