name: Generate gRPC code
on:
  push:
    branches: main
    # paths:
    #   - 'rpc/**'
jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Buf
        run: |
          brew install bufbuild/buf/buf

      - name: Generate Go Code
        run: |
          buf generate

      - name: Commit and Push Generated Code
        run: |
          git config user.name "gRPC Bot"
          git config user.email "grpc@example.com"
          git pull
          git add -A
          git commit -m "chore: regenerate grpc code"
          git push