name: Generate gRPC code
on:
  push:
    branches: main
    paths:
      - 'rpc/**'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Buf
        run: |
          sudo apt-get update
          npm install @bufbuild/buf

      - name: Generate Go Code
        run: |
          npx buf generate

      - name: Commit and Push Generated Code
        run: |
          git config user.name "gRPC Bot"
          git config user.email "grpc@example.com"
          git pull
          git add -A
          git commit -m "chore: regenerate grpc code"
          git push